<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CatMacro</AssemblyName>
    <RootNamespace>CatMacro</RootNamespace>
    <StartupObject>CatMacro.App</StartupObject>
    <WarningLevel>0</WarningLevel>
    <NoWarn>$(NoWarn);NU1701;NETSDK1137</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
